### ISSUE TITLE
Прогресс-бар таймина трека в конце номера может зависнуть на 100%

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/FestEngine#119]
Это гейзенбаг, воспроизводится только на винде, и на Windows 7 намного чаще

**Comment by Oreolek** [comment]
Зависнуть в смысле виснет вся прога или просто не позволяет на следующий трек переключиться?

**Comment by Oreolek** [comment]
Может, это как-то связано с #15 ещё

**Comment by Himura2la** [comment]
нет, просто залипает на 100% вместо нуля. При чем в основном после принудительного завершения номера.
Я в рамках #15 пытался от этого избавиться, и на десятке очень часто все норм, но на семере почему-то не обнуляется (

**Comment by KotovP** [comment]
На KDf случилась странная дичь, которая заруинила нам номер. Прогресс-бар залип не на 100%, а на нуле. Треки запускались спокойно, но сама полоса не менялась вообще. Помогло снятие номера через shift+f2 (к несчастью ошибочное :с )

**Comment by Himura2la** [comment]
@KotovP ого, у меня такого не было никогда. Может дело в самом треке - кривая длительность почему-то? А оно воспроизводится или один раз в жизни случилось?

Однако, было интересно узнать что FE применялся на вашем ивенте, можно Вас попросить добавиться в файлик USES.md

**Comment by Himura2la** [comment]
А ещё, я рекомендую использовать версию для VLC 2.2.8, питоновская либа с ней стабильнее работает. 
И скачать вчерашний билд, я там проблему с невозможностью очистить путь к файлу пофиксил

**Comment by KotovP** [comment]
@Himura2la сам трек это изначально видос формата mov который вообще не открывался. Через Premiere превратил его в мп4, и всё стало открываться. Может тут собака зарыта

**Comment by Himura2la** [comment]
@KotovP, 
Вообще, mov есть в списке расширений видео https://github.com/Himura2la/FestEngine/blob/master/src/constants.py#L48 
Если его VLC открывает, то FestEngine тоже должен... 
Если вдруг получится получить рабочий метод воспроизведения ошибки, будет очень полезно.

**Comment by Himura2la** [comment]
думаю это пофикшено тут https://github.com/Himura2la/FestEngine/commit/f21154293eda6d2b4242d313908e8af53c6debde#diff-2588f2a0547343e2fff83ca457bef067fb4f115375268ae755534f9f62847030R1152
