### ISSUE TITLE
Перевести конфиг на utf-8-bom, чтобы notepad.exe его пережёвывал

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/FestEngine#120]

**Comment by Oreolek** [comment]
если что, wordpad нормально пережёвывает обычный utf-8

**Comment by Himura2la** [comment]
Не подумал... Эта прога не похож на ту которой надо редактировать plain text...

**Comment by Himura2la** [comment]
Нет, он открывает его как 1251 и ничего не может.
