### ISSUE TITLE
Попробывать MPlayer

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/FestEngine#14]
Возможно у VLC есть проблемы с надёжностью. Он начал вешать всё когда я попытался вместо таймера обновлять прогрессбар по ивентам. Подписка на ивенты приводит к нестабильности, да и отсутствие нормальной доки тоже немного напрягает...

Надо отбренчеваться и попробывать вкрячить mplayer

**Comment by FreeSlave** [comment]
Почему не mpv, он поновее и есть libmpv

**Comment by Himura2la** [comment]
можно. mplayer просто первое что гуглится и есть куча инструкций как его подружить с wx

**Comment by Himura2la** [comment]
Кажется, vlc уже не выскрести даже при большом желании (
