### ISSUE TITLE
Перерыв неизвестной длительности

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#147]
Хотелка: перерыв до указанного времени. То есть, мы знаем что следующий блок начинается в 15:00, но не знаем насколько задержится этот блок. Когда мы дойдём до строчки с перерывом, у нас может быть 14:00, а может быть 14:15. Вот чтобы не пересчитывать длину перерыва, хотелось бы указать что он идёт сколько угодно, но заканчивается конкретно по часам.

**Comment by enerdzaiser** [comment]
Уже реализовано! Можно написать 45m 23 нояб. 2019 г. 4:57 ПП пользователь Alexander Yakovlev <notifications@github.com> написал:Хотелка: перерыв до указанного времени. То есть, мы знаем что следующий блок начинается в 15:00, но не знаем насколько задержится этот блок. Когда мы дойдём до строчки с перерывом, у нас может быть 14:00, а может быть 14:15. Вот чтобы не пересчитывать длину перерыва, хотелось бы указать что он идёт сколько угодно, но заканчивается конкретно по часам.

**Comment by Oreolek** [comment]
ок. Не знал, что так уже можно.
