### ISSUE TITLE
[Feature request] Перебиндинг клавиш

### ISSUE THREAD

**Issue by Ponywka** [Himura2la/FestEngine#168]
Хотелось бы видеть возможность перебиндинга клавиш. ESC достаточно легко задеть и в меня так один раз [прилетели ножницы от косплеерши](https://t.me/ponywkaBlog/32) :)

Условно чтобы можно было заменить кнопку "ESC" на какой-нибудь "Q", либо же вообще "CTRL+Q", чтобы точно случайно не отменить выступление.

**Comment by Himura2la** [comment]
блин, жаль что так вышло, сочувствую... Я стараюсь мега аккуратно юзать комп на котором держится шоу, каждое нажатие клавиш по 3 раза проверяю если номер идет... Иногда надо как раз наоборот срочно прервать номер, если у участника что-то пошло не так и он сигнаризрует руками ❌
Думаю, можно пересобрать для тебя с кастомными клавишами, они вот тут настраиваются, если кинешь MR, соберу ^^
https://github.com/Himura2la/FestEngine/blob/master/src/main.pyw#L275

**Comment by Himura2la** [comment]
Сорри, что не отвечал, кажется у меня что-то не так с уведомлениями Т_Т

**Comment by Ponywka** [comment]
Спасибо за ответ! ❤️
