### ISSUE TITLE
Плейлист вместо регэкспов

### ISSUE THREAD

**Issue by FreeSlave** [Himura2la/FestEngine#17]
Полагаться на регэкспы в конечном приложении - плохая затея.
Во-первых, не все знают регэкспы.
Во-вторых не все приводят названия файлов к одинаковому виду.
Я бы лучше позволил составлять плейлисты. Возможно понадобиться создать свой формат - он должен быть текстовым и простым в редактировании. Также можно сделать составление плейлиста прямо в графическом интерфейсе.
@Himura2la, ты, как любитель автоматизма, по-прежнему сможешь создавать такой плейлист гоняя собственный скрипт по своим файлам и собирая их регэкспом.

**Comment by Himura2la** [comment]
#6 и #12 тогда сами заимплементятся, но надо обязательно проверять все пути и при отсутствии каких-то файлов помечать строку ВЫРВИГЛАЗНО КРОВАВО КРАСНЫМ ЧТОБ БЫЛО ЗАМЕТНО С АЛЬФА ЦЕНТАВРЫ

**Comment by FreeSlave** [comment]
Давай тогда подумаем, какие в этом формате поля должны быть.
background - путь к картинке для задника (может ли их быть несколько?)
music - путь к файлу звукового сопровождения
video - путь к файлу видео (видимо, использование вместе с music и background должно быть запрещено, т.е. либо видео, либо музыка с фоновым изображением)

Дополнительные:
start - политика включения музыки/видео
nom - номинация
num - номер заявки
notes - комментарий
Любые другие дополнительные поля (например, должна ли циклиться музыка)

Возможно id, но я не совсем понимаю, зачем он, если это просто порядковый номер.

**Comment by Himura2la** [comment]
Не надо хардкодить поля
[{'path': str, 'info': dict}]

**Comment by Oreolek** [comment]
Поддерживаю. По сути всё равно программа требует большой подготовки файлов.

Сейчас формат базы данных FestEngine основан на простых папках с файлами в определённом формате имён - это не делается 100% вручную. Можно сразу требовать базу данных в более упорядоченном формате.

**Comment by Himura2la** [comment]
ну вообще это как раз не должно делаться вручную и идея была именно в том чтобы избавиться от ошибок типа неверной сортировки. Только файлы и их имена - всё. А вот плейлист можно и вручную нафигачить, и наделать там ошибок. Но я разумеется планирую дополнительную утилитку для авторгенерации плейлиста.
Кстати, не хотелось бы в этой программе связываться с базой данных, я думаю плейлист в формате csv хранить

**Comment by Himura2la** [comment]
Не нравится мне эта карточка. Вот совсем не нравится. Регекспы это фича!
Лучше запилить окошко для организации и автоматического переименования треков

**Comment by Himura2la** [comment]
Короче, поработал я на фесте с Resolume и понял что регексы -- это киллер-фица FestEngine, плейлиста не будет потому что плейлист добавляет много лишней работы, уменьшает надежность системы и отнимает возможность быстро отказаться от FestEngine в пользу любого плеера
