### ISSUE TITLE
Что такое nom, start и num?

### ISSUE THREAD

**Issue by FreeSlave** [Himura2la/FestEngine#19]
Сабж

**Comment by Himura2la** [comment]
- nom -- номинация. В терминах к2 -- код карточки http://tulafest.cosplay2.ru/cards
- start -- пожелание участника по моменту в который надо включать трек. point - с точки (дать выйти на сцену а потом включать), instant - включать пока участник еще закулисами
- num -- номер заявки в к2 уникальный для каждой заявки
![image](https://user-images.githubusercontent.com/7802808/28412247-3e6597ae-6d4c-11e7-9067-7b79ea08251b.png)
