### ISSUE TITLE
Дблятор столбцов может сломаться до перезапуска

### ISSUE THREAD

**Issue by Himura2la** [Himura2la/FestEngine#32]
Возможно при смене фокуса мышкой после ввода заметки

**Comment by FreeSlave** [comment]
Что есть дблятор?

**Comment by Himura2la** [comment]
https://github.com/Himura2la/FestEngine/issues/4

**Comment by Himura2la** [comment]
кек, конечно он ломался, я же хэндлер снимал каждый раз, а при выходе по guard clause обратно не биндил. Guard Clause не всегда делают код лучше ))
