### ISSUE TITLE
Текстовое окно в панели управления

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#41]
Хочется ещё окошка для вывода текста о номере. Хоть из файлов .txt, неважно.
Потому что там можно выводить световой сценарий к номеру, который отправили участники.

**Comment by Himura2la** [comment]
Неплохо, пока нет плейлисов, можно добавить третью папку txt и брать оттуда txt файлы для каждого номера.

**Comment by Himura2la** [comment]
Зачем txt, если можно сразу БД подключать? Думаю, надо добавлить в настройки загрузку БД в формате с2 и выводить нужный набор полей.

**Comment by Himura2la** [comment]
Ну чот похоже что больше нечего сделать

**Comment by Himura2la** [comment]
https://github.com/Himura2la/FestEngine/blob/36ca9fd60fa3139f342f7b479406211980ce22b8/src/text_window.py#L117 это можно тоже в SQL запросе фильтровать

**Comment by Himura2la** [comment]
Это всё еще бета

**Comment by Himura2la** [comment]
Вполне юзабельно в текущем виде
