### ISSUE TITLE
Русская локализация

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#43]
Simply wrap all strings (except those like ZAD, FAD, VID etc.) into the `_()` function and generate the .pot file.

**Comment by Himura2la** [comment]
Нужно просто выделить все строки в ресурсы, собственно локализацию на русский я сделаю, мне просто лень собирать все строки. При чем всякие аббревиатуры типа FAD ZAD VID можно не трогать, они слишком крутые

**Comment by Himura2la** [comment]
все очень просто https://habrahabr.ru/post/73554/

**Comment by Himura2la** [comment]
![image](https://user-images.githubusercontent.com/7802808/33739358-ca99434a-dbad-11e7-8ca3-090d34212741.png)
готово. Были проблемы с `%PYTHON_PATH%\Tools\i18n\pygettext.py`, он не понимал юникод. 
Я сделал так:
```
410: encoding = 'UTF-8' # fp.encoding if fp.encoding else 'UTF-8'
614: fp = open(options.outfile, 'w', encoding='utf-8')
```
Краткий экскурс в локализацию:

- `gettext` собирает все строки из исходников в **.pot** файл
- **.pot** файл загружается в [Poedit](https://poedit.net/), переводится и получается .po файл
- `msgfmt` компилирует **.po** файл в бинарный .mo файл, который используется приложением

**Comment by Himura2la** [comment]
Проблема: если запускать не из папки с папкой locale, он её не найдет. Надо определять местоположение скрипта

**Comment by Himura2la** [comment]
пофиксил
