### ISSUE TITLE
Минимальный список поддерживаемых форматов

### ISSUE THREAD

**Issue by FreeSlave** [Himura2la/FestEngine#47]
Необходимо знать, какие форматы мы намереваемся поддерживать в самодостаточных пакетах.
Например, чтобы убирать лишнее для уменьшения размера или при самостоятельной сборке vlc собирать только то, что нужно.

Пока что мне видится такой минимум:
* mp3, ogg, wav
* avi, mp4 (как минимум с H.264), mkv

Нужен ли flac?

**Comment by Oreolek** [comment]
Да, flac тоже встречается, но его при необходимости можно распаковать в wav.
А вот wmv и wma так просто не сконвертировать, так что IMHO они важнее.

**Comment by Himura2la** [comment]
У нас не так много форматов, мы можем себе позволить поддержать все

**Comment by Himura2la** [comment]
https://github.com/Himura2la/FestEngine/commit/6ed96b2ae125ec37b3c2931d7786455d5653796d

**Comment by Himura2la** [comment]
и еще https://github.com/Himura2la/FestEngine/blob/master/src/constants.py
