### ISSUE TITLE
Не ругаться диалогами о проблемах картинок

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#95]
У нас в лого что-то не понравилось FestEngine с цветовым профилем. Поэтому каждый раз, когда я нажимаю Esc, программа выдаёт окно с ошибкой об этом, приходится закрывать (даже если это просто "ОК").

![1](https://user-images.githubusercontent.com/308627/42132555-c3dc0954-7d09-11e8-94f0-c66df93d3284.png)
[Файл с лого](https://user-images.githubusercontent.com/308627/42132558-d6047134-7d09-11e8-8be1-5c304073e4ba.png)

**Comment by Himura2la** [comment]
http://trac.wxwidgets.org/ticket/15331

Вот тут решение: https://github.com/wxWidgets/wxWidgets/commit/a016e6b896a3d22ccd7a5257154fa80622622048
