### ISSUE TITLE
Хотелка: управление порядком треков

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#96]
Одни участники опоздали, их выход переместили позже. В ДК обнаружилось, что все FMV и AMV будем показывать на большом экране, который долго опускать и поднимать, поэтому FMV и AMV пришлось на лету группировать.

Собственно хотелка - чтобы из FestEngine можно было переставлять порядок треков вверх-вниз. Не заменять файлы друг на друга, а именно как есть, со всей инфой.

**Comment by Himura2la** [comment]
ну блин, это же есть https://github.com/Himura2la/FestEngine/issues/4

**Comment by Himura2la** [comment]
а переставлять чтоб прям переставлялось - такого точно не будет. 
по-хорошему, участники должны знать свои номера и эти номера должны быть написаны на заднике. При перестановке эти номера поменяются и всё придет в хаос
