### ISSUE TITLE
Относительный путь к базе

### ISSUE THREAD

**Issue by Oreolek** [Himura2la/FestEngine#97]
Настройки треков поддерживают относительные пути, а вот путь к базе SQLite может быть только абсолютным.

**Comment by Himura2la** [comment]
с этим путём еще надо посерьезнее запариться, https://github.com/Himura2la/FestEngine/issues/41#issuecomment-366520642 лучше сюда добавь пунктик

**Comment by Himura2la** [comment]
Fixed in 2c711f7
